### ISSUE TITLE
I don't understand how to run this 

### ISSUE THREAD

**Issue by Entity-Data** [olivialba/tog-new-world#1]
"Start the main file using py main.py" means litteraly nothing to me. i tried to run it using python and debug cmd but i cant get it to work and can't find tutorials. i'm not a programer i just like games.

**Comment by olivialba** [comment]
If you have python installed, you can simply run the `start.bat` that is inside the folder, if you don't I can make an executable (.exe) to run

**Comment by Entity-Data** [comment]
i tired using the start.bat file but it just turns off immediately :(

**Comment by olivialba** [comment]
> i tired using the start.bat file but it just turns off immediately :(

I updated it and made a .exe, this is the [link](https://drive.google.com/file/d/1F5G3BawV5rTvlbfGnSyq4JRhD-UGGztW/view), just extract the .zip, open it and run the `ToG Start.exe` inside. It's a bit big since it needs to have a copy of python interpreter and all of its libraries, but it will work even if you dont have python.
